### ISSUE TITLE
Create Initial Project Plan

### ISSUE THREAD

**Issue by iTech75** [awesome-possums/swe574#12]
Initial project plan shall include the following items:

- [x] Possible milestones

- [x] Possible work items for each milestone

- [x] Possible deliverable for each milestone

- [x] Team structure and responsiblities

:dart: 3h

**Comment by iTech75** [comment]
:clock3: 3h
